swav_resnet50:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar]
swav_resnet50w2:
  arch: [resnet50w2]
  pretrained: [checkpoints/self_supervised_pretrain/swav_RN50w2_400ep_pretrain.pth.tar]
swav_resnet50w4:
  arch: [resnet50w4]
  pretrained: [checkpoints/self_supervised_pretrain/swav_RN50w4_400ep_pretrain.pth.tar]
swav_resnet50w5:
  arch: [resnet50w5]
  pretrained: [checkpoints/self_supervised_pretrain/swav_RN50w5_400ep_pretrain.pth.tar]


swav_resnet50_run5:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar]
swav_resnet50_run6:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar]
swav_resnet50_run7:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar]
swav_resnet50_run8:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar]
swav_resnet50_run9:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar]


swav_cat_2:
  arch: [resnet50, resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar]
swav_cat_5:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar]
swav_cat_7:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50, resnet50w2, resnet50w4]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w2_400ep_pretrain.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w4_400ep_pretrain.pth.tar]

swav_cat_8:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50, resnet50w2, resnet50w4, resnet50w5]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w2_400ep_pretrain.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w4_400ep_pretrain.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w5_400ep_pretrain.pth.tar]
seer_32gf:
  arch: [regnet_y_32gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth]
seer_64gf:
  arch: [regnet_y_64gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet64gf.pth]
seer_128gf:
  arch: [regnet_y_128gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet128gf.pth]
seer_256gf:
  arch: [regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet256gf.pth]

seer_32_64:
  arch: [regnet_y_32gf, regnet_y_64gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf.pth]

seer_32_64_128:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf.pth]
seer_32_64_128_256:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf,regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet256gf.pth]
seer_32_64_ft:
  arch: [regnet_y_32gf, regnet_y_64gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf_finetuned.pth]

seer_32_64_128_ft:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf,regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf_finetuned.pth]

seer_32_64_128_256_ft:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf,regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet256gf_finetuned.pth]


supervisedimagenet_resnet50_2:
  arch: [resnet50, resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,]
supervisedimagenet_resnet50_4:
  arch: [resnet50, resnet50, resnet50, resnet50]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run2.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run3.pth.tar]
supervisedimagenet_resnet50_5:
  arch: [resnet50, resnet50, resnet50, resnet50, resnet50]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run2.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run3.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run4.pth.tar]  
supervisedimagenet_resnet50_10:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50, resnet50, resnet50, resnet50, resnet50, resnet50]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run2.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run3.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run4.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run5.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run6.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run7.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run8.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run9.pth.tar,] 


supervisedimagenet_resnet50_run0:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar]
supervisedimagenet_resnet50_run1:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar]
supervisedimagenet_resnet50_run2:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run2.pth.tar]
supervisedimagenet_resnet50_run3:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run3.pth.tar]
supervisedimagenet_resnet50_run4:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run4.pth.tar]
supervisedimagenet_resnet50_run5:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run5.pth.tar]
supervisedimagenet_resnet50_run6:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run6.pth.tar]
supervisedimagenet_resnet50_run7:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run7.pth.tar]
supervisedimagenet_resnet50_run8:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run8.pth.tar]
supervisedimagenet_resnet50_run9:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run9.pth.tar]

supervisedimagenet_resnet50_distill5:
  arch: [resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50_imagenet1k_supervised_distill5.pth.tar]


supervisedimagenet_resnet50w2:
  arch: [resnet50w2 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50w2_imagenet1k_supervised.pth.tar]
supervisedimagenet_resnet50w4:
  arch: [resnet50w4 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50w4_imagenet1k_supervised.pth.tar]
supervisedimagenet_2resnet50:
  arch: [2resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/2resnet50_imagenet1k_supervised.pth.tar]
supervisedimagenet_4resnet50:
  arch: [4resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/4resnet50_imagenet1k_supervised.pth.tar]


