swav_resnet50:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar]
swav_resnet50w2:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_RN50w2_400ep_pretrain.pth.tar]
swav_resnet50w4:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_RN50w4_400ep_pretrain.pth.tar]
swav_resnet50w5:
  arch: [resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_RN50w5_400ep_pretrain.pth.tar]
swav_cat_5:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar]
swav_cat_7:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50, resnet50w2, resnet50w4]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w2_400ep_pretrain.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w4_400ep_pretrain.pth.tar]

swav_cat_8:
  arch: [resnet50, resnet50, resnet50, resnet50,resnet50, resnet50w2, resnet50w4, resnet50w5]
  pretrained: [checkpoints/self_supervised_pretrain/swav_400ep_pretrain.pth.tar, 
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed5.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed6.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed7.pth.tar,
              checkpoints/self_supervised_pretrain/swav_400ep_pretrain_seed8.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w2_400ep_pretrain.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w4_400ep_pretrain.pth.tar,
              checkpoints/self_supervised_pretrain/swav_RN50w5_400ep_pretrain.pth.tar]
seer_32gf:
  arch: [regnet_y_32gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth]
seer_64gf:
  arch: [regnet_y_64gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet64gf.pth]
seer_128gf:
  arch: [regnet_y_128gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet128gf.pth]
seer_256gf:
  arch: [regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet256gf.pth]

seer_32_64:
  arch: [regnet_y_32gf, regnet_y_64gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf.pth]

seer_32_64_128:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf.pth]


seer_32_64_128_256:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf,regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf.pth,
              checkpoints/self_supervised_pretrain/seer_regnet256gf.pth]

seer_32_64_ft:
  arch: [regnet_y_32gf, regnet_y_64gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf_finetuned.pth]

seer_32_64_128_ft:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf,regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf_finetuned.pth]

seer_32_64_128_256_ft:
  arch: [regnet_y_32gf, regnet_y_64gf,regnet_y_128gf,regnet_y_256gf]  
  pretrained: [checkpoints/self_supervised_pretrain/seer_regnet32gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet64gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet128gf_finetuned.pth,
              checkpoints/self_supervised_pretrain/seer_regnet256gf_finetuned.pth]


supervisedimagenet_resnet50_2:
  arch: [resnet50, resnet50 ]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,]

supervisedimagenet_resnet50_4:
  arch: [resnet50, resnet50, resnet50, resnet50, ,resnet50]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run2.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run3.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run4.pth.tar] 
  
supervisedimagenet_resnet50_10:
  arch: [resnet50, resnet50, resnet50, resnet50, ,resnet50, resnet50, ,resnet50, resnet50, ,resnet50, resnet50]
  pretrained: [checkpoints/supervised_pretrain/resnet50/checkpoint_run0.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run1.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run2.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run3.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run4.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run5.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run6.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run7.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run8.pth.tar,
              checkpoints/supervised_pretrain/resnet50/checkpoint_run9.pth.tar,] 


  # elif tag[:len('simsiam_cifar10_resnet18_cat')] == 'simsiam_cifar10_resnet18_cat':
  #   k = int(tag[len('simsiam_cifar10_resnet18_cat'):])
  #   args.arch = ['resnet18'] * k 
  #   args.pretrained = ['results/simsiam_cifar10/cifar10_simsiam_checkpoints/resnet18/run%d/ckpt_epoch_800_1.pth' % i for i in range(k)]

  # elif 'simsiam' in tag:
  #   model = tag.split('_')[1]
  #   k = int(tag.split('_')[2])

  #   args.arch = [model] * k 
  #   args.pretrained = ['results/simsiam_cifar10/cifar10_simsiam_checkpoints/%s/run%d/ckpt_epoch_800_1.pth' % (model, i) for i in range(k) ]
  # elif 'supervisedimagenet' in tag:
  #   model = tag.split('_')[1]
  #   k = int(tag.split('_')[2])

  #   args.arch = [model] * k 
  #   if model == 'resnet50':
  #     args.pretrained = ['results/supervised/imagenet/run%i/checkpoint.pth.tar' % (i) for i in range(k) ]
  #   else:
  #     args.pretrained = ['results/supervised/imagenet/%s/run%i/checkpoint.pth.tar' % (model, i) for i in range(k) ]

  # elif 'supervisedboostimagenet' in tag:
    
  #   model = tag.split('_')[1]
  #   k = int(tag.split('_')[2])

  #   args.arch = [model] * k 
  #   if model == 'resnet50':
  #     args.pretrained = ['results/supervised/imagenet/run0/checkpoint.pth.tar'] + ['results/supervised/imagenet/run0/boost%d/checkpoint.pth.tar' % i for i in range(1,k)]
      
  #   else:
  #     raise NotImplementedError

  
  # else:

  #   raise NotImplementedError

  # return args 



